name: Build

on:
  workflow_call:
  pull_request:
    types: ["opened", "reopened", "synchronize"]
  push:
    branches:
      - main

env:
  NSUnbufferedIO: YES

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

jobs:
  build_ios:
    name: "Build & Test"
    runs-on: [self-hosted, developer-foundations, macOS, ARM64, xcode-latest]

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Build & Test
        id: build-and-test
        run: swift test
